<?php
/**
 * ObjectType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pipeless
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pipeless
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pipeless\Model;
use \Pipeless\ObjectSerializer;

/**
 * ObjectType Class Doc Comment
 *
 * @category Class
 * @description The type of an object. Can be any one of our predefined types. Although it is flexible what object type you use, as a best practice, we suggest you pick the one that relates best to the data you are representing. Doing this also allows specific algos to automatically work with their default settings.
 * @package  Pipeless
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ObjectType
{
    /**
     * Possible values of this enum
     */
    const USER = 'user';
    const PRODUCT = 'product';
    const IMAGE = 'image';
    const COMMENT = 'comment';
    const ARTICLE = 'article';
    const POST = 'post';
    const VIDEO = 'video';
    const CONTENT = 'content';
    const TAG = 'tag';
    const CATEGORY = 'category';
    const APP = 'app';
    const BOOK = 'book';
    const PERSON = 'person';
    const SKILL = 'skill';
    const JOB = 'job';
    const COMPANY = 'company';
    const ACCOUNT = 'account';
    const CARD = 'card';
    const COUNTRY = 'country';
    const STATE = 'state';
    const FILM = 'film';
    const CART = 'cart';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::USER,
            self::PRODUCT,
            self::IMAGE,
            self::COMMENT,
            self::ARTICLE,
            self::POST,
            self::VIDEO,
            self::CONTENT,
            self::TAG,
            self::CATEGORY,
            self::APP,
            self::BOOK,
            self::PERSON,
            self::SKILL,
            self::JOB,
            self::COMPANY,
            self::ACCOUNT,
            self::CARD,
            self::COUNTRY,
            self::STATE,
            self::FILM,
            self::CART,
        ];
    }
}


