<?php
/**
 * V1AppsAppIdEventsEvent1Relationship
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pipeless
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pipeless
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pipeless\Model;

use \ArrayAccess;
use \Pipeless\ObjectSerializer;

/**
 * V1AppsAppIdEventsEvent1Relationship Class Doc Comment
 *
 * @category Class
 * @description When specifying the relationship of the event(s) to delete, if you only specify a type, then all events starting at the start object and going to the end object of the specified type will be deleted. If a created_on datetime is specified too, then only events where the relationship matches the specified type and created_on will be deleted.
 * @package  Pipeless
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V1AppsAppIdEventsEvent1Relationship implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_v1_apps__app_id__events_event_1_relationship';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'type' => 'string',
        'created_on' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'type' => null,
        'created_on' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'created_on' => 'created_on'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'created_on' => 'setCreatedOn'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'created_on' => 'getCreatedOn'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const TYPE_POSTED = 'posted';
    const TYPE_FOLLOWED = 'followed';
    const TYPE_LIKED = 'liked';
    const TYPE_FAVORITED = 'favorited';
    const TYPE_SAVED = 'saved';
    const TYPE_DISLIKED = 'disliked';
    const TYPE_PURCHASED = 'purchased';
    const TYPE_COMMENTED_ON = 'commentedOn';
    const TYPE_CREATED = 'created';
    const TYPE_VIEWED = 'viewed';
    const TYPE_REPORTED = 'reported';
    const TYPE_BLOCKED = 'blocked';
    const TYPE_DELETED = 'deleted';
    const TYPE_AUTHORED = 'authored';
    const TYPE_USED = 'used';
    const TYPE_DISMISSED = 'dismissed';
    const TYPE_LOGGED_IN = 'loggedIn';
    const TYPE_TAGGED_WITH = 'taggedWith';
    const TYPE_CATEGORIZED_IN = 'categorizedIn';
    const TYPE_INTERESTED_IN = 'interestedIn';
    const TYPE_LOCATED_IN = 'locatedIn';
    const TYPE_READ_QUARTER = 'readQuarter';
    const TYPE_READ_HALF = 'readHalf';
    const TYPE_READ_ALL = 'readAll';
    const TYPE_SUBSCRIBED_TO = 'subscribedTo';
    const TYPE_SUBSCRIBED_FROM = 'subscribedFrom';
    const TYPE_ADDED_TO = 'addedTo';
    const TYPE_MADE_BY = 'madeBy';
    const TYPE_PAUSED_ON = 'pausedOn';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_POSTED,
            self::TYPE_FOLLOWED,
            self::TYPE_LIKED,
            self::TYPE_FAVORITED,
            self::TYPE_SAVED,
            self::TYPE_DISLIKED,
            self::TYPE_PURCHASED,
            self::TYPE_COMMENTED_ON,
            self::TYPE_CREATED,
            self::TYPE_VIEWED,
            self::TYPE_REPORTED,
            self::TYPE_BLOCKED,
            self::TYPE_DELETED,
            self::TYPE_AUTHORED,
            self::TYPE_USED,
            self::TYPE_DISMISSED,
            self::TYPE_LOGGED_IN,
            self::TYPE_TAGGED_WITH,
            self::TYPE_CATEGORIZED_IN,
            self::TYPE_INTERESTED_IN,
            self::TYPE_LOCATED_IN,
            self::TYPE_READ_QUARTER,
            self::TYPE_READ_HALF,
            self::TYPE_READ_ALL,
            self::TYPE_SUBSCRIBED_TO,
            self::TYPE_SUBSCRIBED_FROM,
            self::TYPE_ADDED_TO,
            self::TYPE_MADE_BY,
            self::TYPE_PAUSED_ON,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['created_on'] = isset($data['created_on']) ? $data['created_on'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets created_on
     *
     * @return \DateTime|null
     */
    public function getCreatedOn()
    {
        return $this->container['created_on'];
    }

    /**
     * Sets created_on
     *
     * @param \DateTime|null $created_on created_on
     *
     * @return $this
     */
    public function setCreatedOn($created_on)
    {
        $this->container['created_on'] = $created_on;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


