<?php
/**
 * GetActivityFeedResultEventsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pipeless
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pipeless
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Pipeless;

use PHPUnit\Framework\TestCase;

/**
 * GetActivityFeedResultEventsTest Class Doc Comment
 *
 * @category    Class
 * @description GetActivityFeedResultEvents
 * @package     Pipeless
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetActivityFeedResultEventsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetActivityFeedResultEvents"
     */
    public function testGetActivityFeedResultEvents()
    {
    }

    /**
     * Test attribute "actor_object"
     */
    public function testPropertyActorObject()
    {
    }

    /**
     * Test attribute "action_relationship"
     */
    public function testPropertyActionRelationship()
    {
    }

    /**
     * Test attribute "action_object"
     */
    public function testPropertyActionObject()
    {
    }
}
