<?php
/**
 * InlineObject10Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pipeless
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pipeless
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Pipeless;

use PHPUnit\Framework\TestCase;

/**
 * InlineObject10Test Class Doc Comment
 *
 * @category    Class
 * @description InlineObject10
 * @package     Pipeless
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineObject10Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineObject10"
     */
    public function testInlineObject10()
    {
    }

    /**
     * Test attribute "object"
     */
    public function testPropertyObject()
    {
    }

    /**
     * Test attribute "content_object_type"
     */
    public function testPropertyContentObjectType()
    {
    }

    /**
     * Test attribute "primary_positive_relationship_type"
     */
    public function testPropertyPrimaryPositiveRelationshipType()
    {
    }

    /**
     * Test attribute "secondary_positive_relationship_type"
     */
    public function testPropertySecondaryPositiveRelationshipType()
    {
    }

    /**
     * Test attribute "primary_negative_relationship_type"
     */
    public function testPropertyPrimaryNegativeRelationshipType()
    {
    }

    /**
     * Test attribute "content_tagged_relationship_type"
     */
    public function testPropertyContentTaggedRelationshipType()
    {
    }

    /**
     * Test attribute "content_tag_object_type"
     */
    public function testPropertyContentTagObjectType()
    {
    }

    /**
     * Test attribute "coldstart_tag_ids"
     */
    public function testPropertyColdstartTagIds()
    {
    }

    /**
     * Test attribute "limit"
     */
    public function testPropertyLimit()
    {
    }
}
