<?php
/**
 * InlineObject8Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pipeless
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pipeless
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Pipeless;

use PHPUnit\Framework\TestCase;

/**
 * InlineObject8Test Class Doc Comment
 *
 * @category    Class
 * @description InlineObject8
 * @package     Pipeless
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineObject8Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineObject8"
     */
    public function testInlineObject8()
    {
    }

    /**
     * Test attribute "object"
     */
    public function testPropertyObject()
    {
    }

    /**
     * Test attribute "follow_relationship_types"
     */
    public function testPropertyFollowRelationshipTypes()
    {
    }

    /**
     * Test attribute "follow_object_types"
     */
    public function testPropertyFollowObjectTypes()
    {
    }

    /**
     * Test attribute "event_relationship_types"
     */
    public function testPropertyEventRelationshipTypes()
    {
    }

    /**
     * Test attribute "event_object_types"
     */
    public function testPropertyEventObjectTypes()
    {
    }

    /**
     * Test attribute "exclude_self_object"
     */
    public function testPropertyExcludeSelfObject()
    {
    }

    /**
     * Test attribute "limit"
     */
    public function testPropertyLimit()
    {
    }

    /**
     * Test attribute "before"
     */
    public function testPropertyBefore()
    {
    }
}
