<?php
/**
 * V1AppsAppIdEventsEvent1RelationshipTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pipeless
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pipeless
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Pipeless;

use PHPUnit\Framework\TestCase;

/**
 * V1AppsAppIdEventsEvent1RelationshipTest Class Doc Comment
 *
 * @category    Class
 * @description When specifying the relationship of the event(s) to delete, if you only specify a type, then all events starting at the start object and going to the end object of the specified type will be deleted. If a created_on datetime is specified too, then only events where the relationship matches the specified type and created_on will be deleted.
 * @package     Pipeless
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V1AppsAppIdEventsEvent1RelationshipTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1AppsAppIdEventsEvent1Relationship"
     */
    public function testV1AppsAppIdEventsEvent1Relationship()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "created_on"
     */
    public function testPropertyCreatedOn()
    {
    }
}
