<?php
/**
 * V1AppsAppIdEventsBatchEventsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pipeless
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pipeless
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Pipeless;

use PHPUnit\Framework\TestCase;

/**
 * V1AppsAppIdEventsBatchEventsTest Class Doc Comment
 *
 * @category    Class
 * @description An individual event.
 * @package     Pipeless
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V1AppsAppIdEventsBatchEventsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1AppsAppIdEventsBatchEvents"
     */
    public function testV1AppsAppIdEventsBatchEvents()
    {
    }

    /**
     * Test attribute "start_object"
     */
    public function testPropertyStartObject()
    {
    }

    /**
     * Test attribute "relationship"
     */
    public function testPropertyRelationship()
    {
    }

    /**
     * Test attribute "end_object"
     */
    public function testPropertyEndObject()
    {
    }
}
