<?php
/**
 * ActivityApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Pipeless
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pipeless
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Pipeless;

use \Pipeless\Configuration;
use \Pipeless\ApiException;
use \Pipeless\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ActivityApiTest Class Doc Comment
 *
 * @category Class
 * @package  Pipeless
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ActivityApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getActivityActionsFeed
     *
     * Get Activity Actions Feed.
     *
     */
    public function testGetActivityActionsFeed()
    {
    }

    /**
     * Test case for getActivityFeed
     *
     * Get Activity Feed.
     *
     */
    public function testGetActivityFeed()
    {
    }

    /**
     * Test case for getActivityOnObject
     *
     * Get Activity on Object.
     *
     */
    public function testGetActivityOnObject()
    {
    }
}
