<?php
/**
 * GeneralApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Pipeless
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pipeless
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Pipeless;

use \Pipeless\Configuration;
use \Pipeless\ApiException;
use \Pipeless\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GeneralApiTest Class Doc Comment
 *
 * @category Class
 * @package  Pipeless
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GeneralApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createEvent
     *
     * Create Event.
     *
     */
    public function testCreateEvent()
    {
    }

    /**
     * Test case for createEventsBatch
     *
     * Create Events Batch.
     *
     */
    public function testCreateEventsBatch()
    {
    }

    /**
     * Test case for deleteAllObjectsByType
     *
     * Delete All Objects by Type.
     *
     */
    public function testDeleteAllObjectsByType()
    {
    }

    /**
     * Test case for deleteEvent
     *
     * Delete Event.
     *
     */
    public function testDeleteEvent()
    {
    }

    /**
     * Test case for deleteObject
     *
     * Delete Object.
     *
     */
    public function testDeleteObject()
    {
    }

    /**
     * Test case for editObject
     *
     * Edit Object.
     *
     */
    public function testEditObject()
    {
    }

    /**
     * Test case for getObject
     *
     * Get Object.
     *
     */
    public function testGetObject()
    {
    }

    /**
     * Test case for getRecentEvents
     *
     * Get Recent Events.
     *
     */
    public function testGetRecentEvents()
    {
    }
}
